name: language_tool
description: Dart library for checking text for grammar and spelling mistakes
  using the language tool API.
version: 2.1.1
repository: https://github.com/RoundedInfinity/languagetool_api.git
issue_tracker: https://github.com/RoundedInfinity/languagetool_api/issues

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  test: ^1.21.6
  very_good_analysis: ">=3.1.0 <5.0.0"
dependencies:
  http: ^0.13.5
