name: language_tool
description: Dart library for checking text for grammar and spelling mistakes
  using the language tool API.
version: 1.1.0
repository: https://github.com/RoundedInfinity/languagetool_api.git

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  test: ^1.21.6
  effective_dart: ^1.3.2
dependencies:
  http: ^0.13.5
