name: language_tool 
description: Dart library for checking text for grammar and spelling mistakes using the language tool API.  
version: 1.0.0
repository: https://github.com/RoundedInfinity/languagetool_api.git

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  test: ^1.14.4
  effective_dart: ^1.3.0
